### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Emelie4**
Fixed some misspelled words

### CODE REVIEW

**Review by museHD — CHANGES_REQUESTED** [review]
Hey thanks for your input! 

Line 23 should be fine, since a preposition after a verb should be fine and it makes sense with "...angle they are released at"
Also I'm based in Australia so I'm using the British locale where "customisation" with an "s" is a valid spelling :)
(unless of course there is a convention that spelling should be American)

I'm happy to merge the rest of the changes once you revert the ones stated above.

**Comment by Emelie4** [comment]
Yeah, the preposition after a verb is fine since people will understand. I could change it back to customisation, I changed it originally because I'm based in America, and it's with a z here. I never knew about the different spelling.

**Review by Emelie4 — COMMENTED** [review]
Added the preposition and s back

**Comment by museHD** [comment]
Thank you for your contribution @Emelie4 
Feel free to raise issues for this or any of my other projects :)

Cheers!

**Pull request merged**
